### ISSUE TITLE
FILTER NOT EXISTS yields extra solutions in multigraph cases

### ISSUE THREAD

**Issue by MJRinne** [aaltodsg/instans#17]
Continuation of issue #12. The current solution doesn't appear to cover the case, where the events are in named graphs (as is the case, when TriG is used as the input format).
## Steps to reproduce:

1) Query (issue17.rq):

PREFIX : http://instans.org/

SELECT DISTINCT ?eve1 ?epc1 WHERE {
  # Match elements in two events
  GRAPH ?g1 {
    ?eve1 a :ObjectEvent ;
          :associatedWithList ?y1 .
    ?y1 :element ?epc1 }
  GRAPH ?g2 {
    ?eve2 a :ObjectEvent ;
          :associatedWithList ?y2 .
    ?y2  :element ?epc2 }
  # Remove common elements
  FILTER NOT EXISTS { ?y2 :element ?epc1 } }

2) Data (issue17.trig):

@prefix : http://instans.org/ .
:G1 { 
  :eve1 a :ObjectEvent ;
        :associatedWithList _:node1 .
  _:node1 a :SetOfElements ;
      :element :first , :second, :third .
}
:G2 {
  :eve2 a :ObjectEvent ;
        :associatedWithList _:node2 .
  _:node2 a :SetOfElements ;
      :element :second , :third, :fourth .
}

3) Command line: $ instans -r issue17.rq --input-blocks=issue17.trig
## What happens:

All the elements are listed as answers (and repeated despite the "DISTINCT"-modifier):

eve1,epc1
http://instans.org/eve1,http://instans.org/first
http://instans.org/eve1,http://instans.org/second
http://instans.org/eve1,http://instans.org/third
http://instans.org/eve2,http://instans.org/second
http://instans.org/eve2,http://instans.org/third
http://instans.org/eve2,http://instans.org/fourth
## What was expected to happen:

The same answer, as issue #12, which is the same query without the TriG input (events in named graphs):

eve1,epc1
http://instans.org/eve1,http://instans.org/first
http://instans.org/eve2,http://instans.org/fourth
## Notes:

Testing with Sesame 2.7.11 using longer lists, it produces the same (expected) answer, whether the events are in named graphs or not.

Could this have something to do with the way block input is handled vs. TriG?

**Comment by szarnyasg** [comment]
Hi!

Working with @szilardracz91 we discovered a related issue: INSTANS does not handle "negative edge conditions" properly. Based on the [W3C SPARQL specification](http://www.w3.org/TR/rdf-sparql-query/#func-bound), we prepared a sample with a short README here: https://github.com/szarnyasg/instans-bound

The `query-not-bound.sparql` should not return the resource `Bob`, but it does. We also tried to formulate the query with the `FILTER NOT EXISTS` construct in SPARQL 1.1 but gives the same erroneous result.

Thanks,
Gabor
