### ISSUE TITLE
Code not compiling

### ISSUE THREAD

**Issue by Gillani0** [aaltodsg/instans#33]
After all me efforts, I still can't seems to compile it, I am using the Mac OSX and I am using SBCL 1.2.10. 

I am getting the following errors. Any help would be appreciated . Cheers

((FLET SB-UNIX::RUN-HANDLER :IN SB-SYS:ENABLE-INTERRUPT) 13 #.(SB-SYS:INT-SAP #X051F28E8) #.(SB-SYS:INT-SAP #X051F2950))
0[11] ^CHelp! 11 nested errors. SB-KERNEL:*MAXIMUM-ERROR-DEPTH* exceeded.
Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1002D26B93}>
Help! 11 nested errors. SB-KERNEL:*MAXIMUM-ERROR-DEPTH* exceeded.
Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1002D26B93}>
^C
debugger invoked on a SB-SYS:INTERACTIVE-INTERRUPT in thread
#<THREAD "main thread" RUNNING {1002D26B93}>:
  Interactive interrupt at #x7FFF8641A3F6.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE] Return from SB-UNIX:SIGINT.
  1: [ABORT   ] Exit debugger, returning to top level.

("bogus stack frame")
0]

**Comment by MJRinne** [comment]
I have been using 1.1.16 until now and the current version compiled fine on it. Upgrading to 1.2.10, it fails for me too. Unfortunately with a different error:

--- 
; file: /path/instans/src/util/trie.lisp
; in: DEFINE-CLASS TRIE
;     (INSTANS::DEFINE-CLASS INSTANS::TRIE NIL
;                            ((INSTANS::LEVEL :ACCESSOR INSTANS::TRIE-LEVEL
;                              :INITFORM NIL)
;                             (INSTANS::LEVEL-TAIL :ACCESSOR
;                              INSTANS::TRIE-LEVEL-TAIL :INITFORM NIL)))
; 
; caught ERROR:
;   (during macroexpansion of (DEFINE-CLASS TRIE ...))
;   The function INSTANS::PREDICATE-NAME is undefined.

debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
#<THREAD "main thread" RUNNING {1002D26B63}>:
  COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "instans" "util" "trie">

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<CL-SOURCE-FILE "instans" "util" "trie">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<CL-SOURCE-FILE "instans" "util" "trie">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4: [RETRY                        ] Retry EVAL of current toplevel form.
  5: [CONTINUE                     ] Ignore error and continue loading file "/path/instans/src/docompile.lisp".
  6: [ABORT                        ] Abort loading file "/path/instans/src/docompile.lisp".
  7:                                 Ignore runtime option --load "docompile.lisp".
  8:                                 Skip rest of --eval and --load options.
  9:                                 Skip to toplevel READ/EVAL/PRINT loop.
 10: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

(UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "instans" "util" "trie">)))
--- 

Thanks for the heads up! For an immediate fix SBCL 1.1.16 had no problems on Mavericks. For 1.2.10, the problem needs to be located first.

**Comment by Gillani0** [comment]
Alright no worries, any suggestions how to install the older version of sbcl? as homebrew only supports the new version, and the versions from 1.1.10 onwards doesn't provide the pre-built Mac version for sbcl. Cheers

**Comment by MJRinne** [comment]
Not without trying, so far I've always followed the latest version both with and without brew. As a very first quick&dirty solution, what if you just download the binary from here:
https://drive.google.com/file/d/0B3om5aa6_GwHYkFvWUtxLUxKc00/view?usp=sharing
...into the instans/bin directory, type "instans" there and press enter. If it prints a list of command line parameters, it should be ok.
It is compiled with SBCL 1.1.16 under Mavericks, so it shouldn't be too different. The config script also loads some test data, but that is not critical for operation.

**Comment by Gillani0** [comment]
Alright, thanks a million.

**Comment by MJRinne** [comment]
Thanks for the good housekeeping, but I'd still vote to keep this open as the actual problem (compilation fails with new SBCL versions) needs fixing.

**Comment by MJRinne** [comment]
Documentation still needs to be updated, but the build process has now been completely rewritten by Esko. It is now using [buildapp](http://www.xach.com/lisp/buildapp/), which is available in [brew](http://brew.sh/). Brewing buildapp will also update sbcl.

After installing buildapp, start with `./configure` as before. It will now create a makefile. "make all" should do the compilation.
